version: '3.7'

services:
  backend:
    image: ghcr.io/${GHCR_OWNER}/onboarding-portal-backend:${IMAGE_TAG:-latest}
    build:
      context: .
    env_file: .env
    ports:
      - "8081:8081"
    networks:
      - devnet
    volumes:
      - sqlite:/app/db
      - uploads:/app/uploads
      - ./keys:/app/keys:ro

networks:
  devnet:
    driver: bridge

volumes:
  sqlite:
  uploads:
