blank_issues_enabled: true
contact_links:
  - name: Security issue
    url: https://github.com/iSHAREScheme/participant-onboarding-portal/security/advisories/new
    about: "Please report security issues via GitHub Security Advisories."
